### ISSUE TITLE
Toolset update in Stringholders

### ISSUE THREAD

**Issue by LukasBudach** [hpi-swa-teaching/SWT18-Project-04#11]
There is an issue concerning the updating of the used default Toolset in already opened Stringholders. These include (but may not be restricted to) the Workspace and every editable field in the Browser.
The issue manifests itself in an irregular manner and only after doing the following:
- Swapping the default ToolSet to be the ACToolSet
- Editing something in a StringHolder, triggering our correction to kick in
- Swapping back to the ToolSet used before inserting the ACToolSet
After those steps editing in the same StringHolder, that used the correction, sometimes the autocorrection will continue overwriting the autocompletion. This however is not the only problem, as some changes made to our own correction do not deploy to StringHolders that were opened before they were implemented (one of those would be the StringHolder we write the code changes in).

This issue does need some more research into it.
It does however also need to be fixed, as the user cannot be expected to deal with a system not behaving as he wants it to.

**Comment by LukasBudach** [comment]
The issue may be resolvable by implementing a function, triggered by a swap in preferences, checking all of the currently existent StringHolders and manually swapping their text-processing classes.

**Comment by LukasBudach** [comment]
The issue does not occur if you did not write in the StringHolder after enabling our Autocorrection, probably due to the Controller not being initialized in this case.

**Comment by andronymoid** [comment]
Similar problem, probably same bug: if you open the extended menu, close it and then resume typing, the extended menu appears right away

**Comment by LukasBudach** [comment]
Issue should be fixed now by going brute force through all StringHolders and refreshing their Controller once our ToolSet is set or reset
