### ISSUE TITLE
refresh lookup tables

### ISSUE THREAD

**Issue by LukasBudach** [hpi-swa-teaching/SWT18-Project-04#18]
Find a smart way to refresh the contents of our own lookup tables.

**Comment by Portoso** [comment]
The dates in the OCompletionTable get updated when you write a word using the OCompletion.
When you use our AutoCorrection that doesn't happen.
We should find a way to change that.

**Comment by LukasBudach** [comment]
The ACTable is now updating each time you save a freshly written method. Also we don't rely upon loading of the OCompletionTable anymore. This decreases the quality of our recommendations in the beginning, but cuts further ties to OCompletion.
