### ISSUE TITLE
Deleting in real-time

### ISSUE THREAD

**Issue by LukasBudach** [hpi-swa-teaching/SWT18-Project-04#33]
AS A squeak developer
I WANT TO be able to delete in real-time, while also getting updated suggestions after a small delay (to allow for more stuff to be deleted)
SO THAT I can delete bigger patches without performance loss, while still getting recommendations after I'm done deleting

**Comment by Portoso** [comment]
we should find a better way to delete in realtime without flipping a coin.

**Comment by LukasBudach** [comment]
not gonna get much better
